window.addEventListener('load',function(){var requiredInputElements=document.querySelectorAll('input[required], textarea[required]');requiredInputElements.forEach(function(requiredElement,index){let after=document.createElement('div');after.classList.add('input-alert');after.innerHTML='!';after.style.position=`absolute`;after.style.top=`0.5rem`;after.style.right=`0.5rem`;let inputWrapper=document.createElement('div');inputWrapper.classList.add('input-wrapper');inputWrapper.style.position=`relative`;requiredElement.before(inputWrapper)
inputWrapper.appendChild(requiredElement)
inputWrapper.appendChild(after)});var subscriptionForm=document.querySelector('#form-subscribe');subscriptionForm.addEventListener('submit',function(event){event.preventDefault();var server=subscriptionForm.getAttribute("action");if(!server){server='ajaxserver/serverfile.php'}
var name=subscriptionForm.querySelector("#name-subscribe").value;var email=subscriptionForm.querySelector("#email-subscribe").value;var user={name:name,email:email,submit_email:'submit_email',};_subscribeUser(user,server);})
function _subscribeUser(user,server){axios.post(server,user).then(response=>{var responseData=response.data;console.log(`POST success`,responseData);subscriptionForm.classList.add('form-success')}).catch(error=>{console.error(error)
subscriptionForm.classList.add('form-error')})}
var messageModal=new bootstrap.Modal(document.getElementById('messageModal'));var messageForm=document.querySelector('#form-message');messageForm.addEventListener('submit',function(event){event.preventDefault();var server=messageForm.getAttribute("action");if(!server){server='ajaxserver/serverfile.php'}
var name=messageForm.querySelector("#name-message").value;var email=messageForm.querySelector("#email-message").value;var message=messageForm.querySelector("#message-message").value;var content={name:name,email:email,message:message,submit_message:'submit_message',};_sendMessage(content,server);})
function _sendMessage(content,server){axios.post(server,content).then(response=>{var responseData=response.data;console.log(`POST success`,responseData);subscriptionForm.classList.add('form-success');messageModal.hide();messageForm.querySelectorAll('input, textarea').forEach(function(inputElement){inputElement.value='';});}).catch(error=>{console.error(error)
subscriptionForm.classList.add('form-error')})}});